server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel-cloud-home?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  profiles:
    include: common
    active: dev

management:
  # 端点启用配置
  endpoint:
    logfile:
      # 启用返回日志文件内容的端点
      enabled: true
      # 外部日志文件路径
      external-file: logs/novel-home-service.log

